//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Generator.Resources.SQLRes", typeof(SQLRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\BlobData.sql.
        /// </summary>
        internal static string BlobDataFileName {
            get {
                return ResourceManager.GetString("BlobDataFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\CennikUkonov.sql.
        /// </summary>
        internal static string CennikUkonovFileName {
            get {
                return ResourceManager.GetString("CennikUkonovFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\Choroba.sql.
        /// </summary>
        internal static string ChorobaFileName {
            get {
                return ResourceManager.GetString("ChorobaFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\Dokument.sql.
        /// </summary>
        internal static string DokumentFileName {
            get {
                return ResourceManager.GetString("DokumentFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO {0} VALUES({1});.
        /// </summary>
        internal static string InsertStatement {
            get {
                return ResourceManager.GetString("InsertStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\LekarskyUkon.sql.
        /// </summary>
        internal static string LekarskyUkonFileName {
            get {
                return ResourceManager.GetString("LekarskyUkonFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\Liek.sql.
        /// </summary>
        internal static string LiekFileName {
            get {
                return ResourceManager.GetString("LiekFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\Lozko.sql.
        /// </summary>
        internal static string LozkoFileName {
            get {
                return ResourceManager.GetString("LozkoFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\MedicinskyNastroj.sql.
        /// </summary>
        internal static string MedicinskyNastrojFileName {
            get {
                return ResourceManager.GetString("MedicinskyNastrojFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\Nemocnica.sql.
        /// </summary>
        internal static string NemocnicaFileName {
            get {
                return ResourceManager.GetString("NemocnicaFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\Ockovanie.sql.
        /// </summary>
        internal static string OckovanieFileName {
            get {
                return ResourceManager.GetString("OckovanieFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\Oddelenie.sql.
        /// </summary>
        internal static string OddelenieFileName {
            get {
                return ResourceManager.GetString("OddelenieFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\Osoby.sql.
        /// </summary>
        internal static string OsobaFileName {
            get {
                return ResourceManager.GetString("OsobaFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\Pacienti.sql.
        /// </summary>
        internal static string PacientFileName {
            get {
                return ResourceManager.GetString("PacientFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\Personal.sql.
        /// </summary>
        internal static string PersonalFileName {
            get {
                return ResourceManager.GetString("PersonalFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\Platba.sql.
        /// </summary>
        internal static string PlatbaFileName {
            get {
                return ResourceManager.GetString("PlatbaFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\Poistenie.sql.
        /// </summary>
        internal static string PoistenieFileName {
            get {
                return ResourceManager.GetString("PoistenieFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\Pristroj.sql.
        /// </summary>
        internal static string PristrojFileName {
            get {
                return ResourceManager.GetString("PristrojFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\SkladLiekovOddelenia.sql.
        /// </summary>
        internal static string SkladLiekovOddeleniaFileName {
            get {
                return ResourceManager.GetString("SkladLiekovOddeleniaFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\Vozidlo.sql.
        /// </summary>
        internal static string VozidloFileName {
            get {
                return ResourceManager.GetString("VozidloFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\VyjazdovyTym.sql.
        /// </summary>
        internal static string VyjazdovyTymFileName {
            get {
                return ResourceManager.GetString("VyjazdovyTymFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\ZabrateLozka.sql.
        /// </summary>
        internal static string ZabrateLozkaFileName {
            get {
                return ResourceManager.GetString("ZabrateLozkaFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\ZdravotnaKarta.sql.
        /// </summary>
        internal static string ZdravotnaKartaFileName {
            get {
                return ResourceManager.GetString("ZdravotnaKartaFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\ZoznamChorob.csv.
        /// </summary>
        internal static string ZoznamChorobFileName {
            get {
                return ResourceManager.GetString("ZoznamChorobFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\ZoznamLiekov.sql.
        /// </summary>
        internal static string ZoznamLiekovFileName {
            get {
                return ResourceManager.GetString("ZoznamLiekovFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\ZoznamLiekov.csv.
        /// </summary>
        internal static string ZoznamLiekovFileName2 {
            get {
                return ResourceManager.GetString("ZoznamLiekovFileName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\ZoznamOchoreni.sql.
        /// </summary>
        internal static string ZoznamOchoreniFileName {
            get {
                return ResourceManager.GetString("ZoznamOchoreniFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\ZoznamOckovani.sql.
        /// </summary>
        internal static string ZoznamOckovaniFileName {
            get {
                return ResourceManager.GetString("ZoznamOckovaniFileName", resourceCulture);
            }
        }
    }
}
